export const createSchema = `
CREATE TABLE IF NOT EXISTS configAppConfig (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS configDataConfig (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS configDateCongress (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS configTemplateConfig (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS programmeSpeakers (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS programmeScheduleScientific (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS programmeFiltersScientific (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS programmeScheduleTraining (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS programmeFiltersTraining (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS programmeScheduleVod (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS programmeFiltersVod (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS programmeScheduleSubCongress (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS programmeFiltersSubCongress (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS exhibitorsContent (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS exhibitorsFilters (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS exhibitorsProducts (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS abstractsContent (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS abstractsFilters (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS interactiveMap (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS interactiveMapAssociations (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS generalInformation (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS certificateAttendance (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS neuralQuizz (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS replay (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS jobs (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS inscription (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS cgu (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS customPages (id INTEGER PRIMARY KEY NOT null, data TEXT);
CREATE TABLE IF NOT EXISTS needUpdateVersion (id INTEGER PRIMARY KEY NOT null, data TEXT);
`;

export const deleteSchema = `
DELETE FROM configAppConfig WHERE 1;
DELETE FROM configDataConfig WHERE 1;
DELETE FROM configDateCongress WHERE 1;
DELETE FROM configTemplateConfig WHERE 1;
DELETE FROM programmeSpeakers WHERE 1;
DELETE FROM programmeScheduleScientific WHERE 1;
DELETE FROM programmeFiltersScientific WHERE 1;
DELETE FROM programmeScheduleTraining WHERE 1;
DELETE FROM programmeFiltersTraining WHERE 1;
DELETE FROM programmeScheduleVod WHERE 1;
DELETE FROM programmeFiltersVod WHERE 1;
DELETE FROM programmeScheduleSubCongress WHERE 1;
DELETE FROM programmeFiltersSubCongress WHERE 1;
DELETE FROM exhibitorsContent WHERE 1;
DELETE FROM exhibitorsFilters WHERE 1;
DELETE FROM exhibitorsProducts WHERE 1;
DELETE FROM abstractsContent WHERE 1;
DELETE FROM abstractsFilters WHERE 1;
DELETE FROM interactiveMap WHERE 1;
DELETE FROM interactiveMapAssociations WHERE 1;
DELETE FROM generalInformation WHERE 1;
DELETE FROM certificateAttendance WHERE 1;
DELETE FROM neuralQuizz WHERE 1;
DELETE FROM replay WHERE 1;
DELETE FROM jobs WHERE 1;
DELETE FROM inscription WHERE 1;
DELETE FROM cgu WHERE 1;
DELETE FROM customPages WHERE 1;
DELETE FROM needUpdateVersion WHERE 1;
`;
